# Generated by Django 3.2.6 on 2021-08-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoritesmodel',
            old_name='pizza_size_is',
            new_name='pizza_size',
        ),
        migrations.RenameField(
            model_name='userfavoritesmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
