# Generated by Django 3.2.7 on 2021-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customusermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
