# Generated by Django 3.2.7 on 2021-09-16 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0002_rename_pizza_id_pizzasizemodel_pizza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='created', max_length=24)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('confirmation_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_start_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.TimeField(default=datetime.time(0, 0))),
                ('delivery_address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=4)),
                ('comment', models.CharField(max_length=200)),
                ('total', models.SmallIntegerField(default=0)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderPizzaSizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pizza', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='order.ordermodel')),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.pizzasizemodel')),
            ],
            options={
                'db_table': 'order_pizza',
            },
        ),
    ]
