# Generated by Django 3.2.6 on 2021-08-23 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(max_length=11)),
                ('confirmation_time', models.DateTimeField()),
                ('delivery_start_time', models.DateTimeField()),
                ('delivery_end_time', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=4)),
                ('comment', models.CharField(max_length=200)),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivers', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderPizzaSizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pizza', models.SmallIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='order.ordermodel')),
                ('pizza_size_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.pizzasizemodel')),
            ],
            options={
                'db_table': 'order_pizza',
            },
        ),
    ]
