# Generated by Django 3.2.6 on 2021-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total',
            field=models.SmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
