# Generated by Django 3.2.6 on 2021-08-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpizzasizemodel',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderpizzasizemodel',
            old_name='pizza_size_id',
            new_name='pizza_size',
        ),
    ]
