# Generated by Django 3.2.6 on 2021-08-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210823_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='courier_id',
            new_name='courier',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
