# Generated by Django 3.2.7 on 2021-09-17 10:39

import apps.pizza.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('ingredients', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=15)),
                ('image', models.FileField(default=None, upload_to=apps.pizza.services.upload_to)),
            ],
            options={
                'db_table': 'pizzas',
            },
        ),
        migrations.CreateModel(
            name='PizzaSizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.CharField(max_length=5)),
                ('weight', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pizza.pizzamodel')),
            ],
            options={
                'db_table': 'pizza_sizes',
            },
        ),
    ]
