# Generated by Django 3.2.7 on 2021-09-21 12:35

import apps.pizza.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='image',
            field=models.FileField(upload_to=apps.pizza.services.upload_to),
        ),
    ]
